## Author

- **Name:** Shuo Wang, Jiateng Wang
- **Email:** shuow6@illinois.edu, jiateng3@illinois.edu

## Purpose

Our pokemon application is aimed at summarizing pokemons' statistics across all 8 generations. For the data visualization,  a histogram can be created to describe the distribution of pokemon's types, when users select a specific generation and determine the range of pokemon's weights and heights. The range of weight and height has a dependency on the generation. When users select different generations, the range of weight and height will change accordingly. For the table, my application lists the necessary information about pokemons. The summary table shows a summary of the strength of each generation of pokemons. This Pokemon Application could be used to check the strength of pokemons.

## Data

- name: The English name of the Pokemon
- japanese_name: The Original Japanese name of the Pokemon
- pokedex_number: The entry number of the Pokemon in the National Pokedex
- percentage_male: The percentage of the species that are male. Blank if the Pokemon is genderless.
- type_1: The Primary Type of the Pokemon
- type_2: The Secondary Type of the Pokemon
- species: The Classification of the Pokemon as described by the Sun and Moon Pokedex
- height_m: Height of the Pokemon in metres
- weight_kg: The Weight of the Pokemon in kilograms
- capture_rate: Capture Rate of the Pokemon
- baseeggsteps: The number of steps required to hatch an egg of the Pokemon
- abilities: A stringified list of abilities that the Pokemon is capable of having
- experience_growth: The Experience Growth of the Pokemon
- base_happiness: Base Happiness of the Pokemon
- against_?: Eighteen features that denote the amount of damage taken against an attack of a particular type
- hp: The Base HP of the Pokemon
- attack: The Base Attack of the Pokemon
- defense: The Base Defense of the Pokemon
- sp_attack: The Base Special Attack of the Pokemon
- sp_defense: The Base Special Defense of the Pokemon
- speed: The Base Speed of the Pokemon
- generation: The numbered generation which the Pokemon was first introduced

## Reference

- [The Complete Pokemon Dataset](https://www.kaggle.com/datasets/mariotormo/complete-pokemon-dataset-updated-090420)
